# Generated by Django 3.1.5 on 2021-03-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210317_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profileImages/defaultImg.jpg', null=True, upload_to='profileImages'),
        ),
    ]
