# Generated by Django 3.1.5 on 2021-03-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_image',
            field=models.ImageField(default='brandImages/defaultBrandImage.jpg', upload_to='brandImages'),
        ),
    ]
