# Generated by Django 3.1.5 on 2021-03-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
