# Generated by Django 3.1.5 on 2021-04-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
