# Generated by Django 3.1.5 on 2021-04-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productreview_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ManyToManyField(related_name='product_review', to='store.Product'),
        ),
    ]
