# Generated by Django 3.1.5 on 2021-03-18 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210318_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='date_purchased',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
