# Generated by Django 3.1.5 on 2021-05-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210502_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='author_image',
            field=models.ImageField(default='user.profile.image', upload_to=''),
        ),
    ]
