# Generated by Django 3.1.5 on 2021-05-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productreview_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='author_image',
        ),
    ]
