# Generated by Django 3.1.5 on 2021-05-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_productreview_author_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='product_rating',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='rating',
            new_name='review_rating',
        ),
    ]
