# Generated by Django 3.1.5 on 2021-03-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210318_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_itmes',
            field=models.IntegerField(default=0),
        ),
    ]
