# Generated by Django 3.1.5 on 2021-03-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_customer_total_itmes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='total_itmes',
            new_name='total_items',
        ),
    ]
