# Generated by Django 3.1.5 on 2021-03-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210319_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='open_basket',
            field=models.BooleanField(default=True),
        ),
    ]
