# Generated by Django 3.1.5 on 2021-03-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_basket_open_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
