# Generated by Django 3.1.5 on 2021-03-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210320_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='sub_category_name',
        ),
    ]
