# Generated by Django 3.1.5 on 2021-03-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20210320_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_sub_category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
