# Generated by Django 3.1.5 on 2021-03-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20210320_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_sub_category',
            new_name='sub_category',
        ),
    ]
