# Generated by Django 3.1.5 on 2021-03-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='company',
        ),
    ]
