# Generated by Django 3.1.5 on 2021-03-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_product_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='times_ordered',
            field=models.IntegerField(default=0),
        ),
    ]
