# Generated by Django 3.1.7 on 2021-03-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onLineStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='quantity_ordered',
            field=models.IntegerField(default=0),
        ),
    ]
