# Generated by Django 3.1.7 on 2021-03-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onLineStore', '0002_auto_20210311_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchse',
            new_name='Purchase',
        ),
    ]
