# Generated by Django 3.1.5 on 2021-03-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onLineStore', '0003_auto_20210312_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.IntegerField(default=0),
        ),
    ]
