# Generated by Django 3.1.5 on 2021-03-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onLineStore', '0004_purchase_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=100000, null=True),
        ),
    ]
