# Generated by Django 3.1.5 on 2021-03-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onLineStore', '0005_auto_20210313_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchase',
        ),
        migrations.AddField(
            model_name='order',
            name='purchase',
            field=models.ManyToManyField(to='onLineStore.Purchase'),
        ),
    ]
