# Generated by Django 3.1.5 on 2021-03-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onLineStore', '0007_auto_20210313_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='date_ordered',
            new_name='date_purchased',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_id',
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='on_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
